version: '3.5'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    ports:
      - '27017:27017'
    container_name: urlshortener-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=123dkb
    image: mongo