version: '3.5'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123dkb
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"