spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: admin
    password: 123dkb

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: true
